"""Fixed Table

Revision ID: 11e1d8ee3bb4
Revises: bb25543752fe
Create Date: 2023-12-21 18:11:57.234420

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '11e1d8ee3bb4'
down_revision = 'bb25543752fe'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('orders', schema=None) as batch_op:
        batch_op.add_column(sa.Column('total_price', sa.Integer(), nullable=True))
        batch_op.drop_column('quantity')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('orders', schema=None) as batch_op:
        batch_op.add_column(sa.Column('quantity', sa.INTEGER(), nullable=True))
        batch_op.drop_column('total_price')

    # ### end Alembic commands ###
