"""Added Models

Revision ID: 265e5a39443f
Revises: 8a28d06b86cd
Create Date: 2023-12-16 16:26:58.973869

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '265e5a39443f'
down_revision = '8a28d06b86cd'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('customers', schema=None) as batch_op:
        batch_op.add_column(sa.Column('address', sa.String(length=80), nullable=True))
        batch_op.add_column(sa.Column('password', sa.String(length=80), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('customers', schema=None) as batch_op:
        batch_op.drop_column('password')
        batch_op.drop_column('address')

    # ### end Alembic commands ###
