"""Added table

Revision ID: 35ba718fbcbd
Revises: e4bebe698d93
Create Date: 2023-12-18 13:54:12.358304

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '35ba718fbcbd'
down_revision = 'e4bebe698d93'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('food', schema=None) as batch_op:
        batch_op.add_column(sa.Column('restaurant', sa.String(length=80), nullable=True))
        batch_op.drop_column('restaurants')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('food', schema=None) as batch_op:
        batch_op.add_column(sa.Column('restaurants', sa.VARCHAR(length=80), nullable=True))
        batch_op.drop_column('restaurant')

    # ### end Alembic commands ###
