"""Added Table

Revision ID: 83c95cef0c6f
Revises: 82f386a24070
Create Date: 2023-12-19 15:23:17.429479

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '83c95cef0c6f'
down_revision = '82f386a24070'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('orders', schema=None) as batch_op:
        batch_op.add_column(sa.Column('food_name', sa.String(length=80), nullable=True))
        batch_op.add_column(sa.Column('customer_name', sa.String(length=80), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('orders', schema=None) as batch_op:
        batch_op.drop_column('customer_name')
        batch_op.drop_column('food_name')

    # ### end Alembic commands ###
