"""Added Table

Revision ID: 8e8f3ed2dbc7
Revises: 83c95cef0c6f
Create Date: 2023-12-19 15:31:23.334640

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8e8f3ed2dbc7'
down_revision = '83c95cef0c6f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('orders', schema=None) as batch_op:
        batch_op.drop_column('food_name')
        batch_op.drop_column('customer_name')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('orders', schema=None) as batch_op:
        batch_op.add_column(sa.Column('customer_name', sa.VARCHAR(length=80), nullable=True))
        batch_op.add_column(sa.Column('food_name', sa.VARCHAR(length=80), nullable=True))

    # ### end Alembic commands ###
