"""Added table

Revision ID: 927e748f0d31
Revises: 35ba718fbcbd
Create Date: 2023-12-18 13:55:22.671521

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '927e748f0d31'
down_revision = '35ba718fbcbd'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('food', schema=None) as batch_op:
        batch_op.add_column(sa.Column('restaurant_name', sa.String(length=80), nullable=True))
        batch_op.drop_column('restaurant')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('food', schema=None) as batch_op:
        batch_op.add_column(sa.Column('restaurant', sa.VARCHAR(length=80), nullable=True))
        batch_op.drop_column('restaurant_name')

    # ### end Alembic commands ###
