"""Added table

Revision ID: 9a5a899b3272
Revises: 09cfe0eada1e
Create Date: 2023-12-18 13:41:43.583515

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9a5a899b3272'
down_revision = '09cfe0eada1e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('restaurant_food')
    with op.batch_alter_table('food', schema=None) as batch_op:
        batch_op.add_column(sa.Column('rest', sa.String(length=80), nullable=True))
        batch_op.add_column(sa.Column('price', sa.Integer(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('food', schema=None) as batch_op:
        batch_op.drop_column('price')
        batch_op.drop_column('rest')

    op.create_table('restaurant_food',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('price', sa.INTEGER(), nullable=False),
    sa.Column('restaurant_id', sa.INTEGER(), nullable=True),
    sa.Column('food_id', sa.INTEGER(), nullable=True),
    sa.ForeignKeyConstraint(['food_id'], ['food.id'], name='fk_restaurant_food_food_id_food'),
    sa.ForeignKeyConstraint(['restaurant_id'], ['restaurants.id'], name='fk_restaurant_food_restaurant_id_restaurants'),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###
