"""Added Table

Revision ID: 9b5b818c76da
Revises: f36c062ae4b7
Create Date: 2023-12-21 16:55:56.246972

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9b5b818c76da'
down_revision = 'f36c062ae4b7'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('restaurant_food', schema=None) as batch_op:
        batch_op.add_column(sa.Column('rating', sa.Integer(), nullable=False))
        batch_op.drop_column('review')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('restaurant_food', schema=None) as batch_op:
        batch_op.add_column(sa.Column('review', sa.VARCHAR(length=80), nullable=True))
        batch_op.drop_column('rating')

    # ### end Alembic commands ###
