"""Added Table

Revision ID: bb25543752fe
Revises: 9b5b818c76da
Create Date: 2023-12-21 17:40:14.848901

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'bb25543752fe'
down_revision = '9b5b818c76da'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('restaurant_food')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('restaurant_food',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('rating', sa.INTEGER(), nullable=False),
    sa.Column('price', sa.INTEGER(), nullable=False),
    sa.Column('restaurant_id', sa.INTEGER(), nullable=True),
    sa.Column('food_id', sa.INTEGER(), nullable=True),
    sa.ForeignKeyConstraint(['food_id'], ['food.id'], name='fk_restaurant_food_food_id_food'),
    sa.ForeignKeyConstraint(['restaurant_id'], ['restaurants.id'], name='fk_restaurant_food_restaurant_id_restaurants'),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###
