"""Added table

Revision ID: e4bebe698d93
Revises: 9a5a899b3272
Create Date: 2023-12-18 13:50:00.075656

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e4bebe698d93'
down_revision = '9a5a899b3272'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('food', schema=None) as batch_op:
        batch_op.add_column(sa.Column('restaurants', sa.String(length=80), nullable=True))
        batch_op.drop_column('rest')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('food', schema=None) as batch_op:
        batch_op.add_column(sa.Column('rest', sa.VARCHAR(length=80), nullable=True))
        batch_op.drop_column('restaurants')

    # ### end Alembic commands ###
