"""Added Table

Revision ID: f36c062ae4b7
Revises: 8e8f3ed2dbc7
Create Date: 2023-12-21 16:52:44.437920

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f36c062ae4b7'
down_revision = '8e8f3ed2dbc7'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('restaurant_food',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('price', sa.Integer(), nullable=False),
    sa.Column('restaurant_id', sa.Integer(), nullable=True),
    sa.Column('food_id', sa.Integer(), nullable=True),
    sa.Column('review', sa.String(length=80), nullable=True),
    sa.ForeignKeyConstraint(['food_id'], ['food.id'], name=op.f('fk_restaurant_food_food_id_food')),
    sa.ForeignKeyConstraint(['restaurant_id'], ['restaurants.id'], name=op.f('fk_restaurant_food_restaurant_id_restaurants')),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('restaurant_food')
    # ### end Alembic commands ###
